### ISSUE TITLE
Can't edit Android System ID

### ISSUE THREAD

**Issue by nominath654** [sdex/AndroidIDeditor#2]
Hi, I know this is 99% done on purpose, but I was wondering if there was any way to remove this restriction, as I need to change Android system id currently, to get around the Spotify premium trial detection. Thanks :)

**Comment by sdex** [comment]
Yes, it's easy to remove the restriction, but I don't think the Spotify app can access that id - it breaks whole idea of the new ids mechanism. The changing may harm your device, so create backup at least.

**Comment by sdex** [comment]
https://github.com/sdex/AndroidIDeditor/releases/tag/1.1

**Comment by nominath654** [comment]
Changing Spotify ID didn't do anything, still said I had already done a free trial. Any idea what they might be looking for? Mac address or IP maybe? Also thanks for the quick response and release of 1.1 I appreciate it :)

**Comment by sdex** [comment]
There are too much identifiers. Try [XPrivacyLua](https://repo.xposed.info/module/eu.faircode.xlua) if you have xposed.
