### ISSUE TITLE
Export ids to txt file

### ISSUE THREAD

**Issue by dizietsma** [sdex/AndroidIDeditor#5]
Option to export ids to txt file on external storage wold be cool.:)
Plus, your blog post doesn't explain the two ids for each app - why can't they be the same?

diziet

**Comment by sdex** [comment]
Sorry for the late reply. 
AFAIR, during testing, it did work when ids were the same, I didn't bother with that and just made them different. 
So, it might work or might not. 
More implementation details you can find in `SettingsProvider`:
https://github.com/aosp-mirror/platform_frameworks_base/blob/master/packages/SettingsProvider/src/com/android/providers/settings/SettingsProvider.java
Regarding exporting, it is just simple file copying so I didn't find it very useful. Also, the app creates a backup file in the same directory.

**Comment by sdex** [comment]
The new version of the app supports exporting IDs:
https://github.com/sdex/AndroidIDeditorV2
This app is not under active development.
