### ISSUE TITLE
App not listed

### ISSUE THREAD

**Issue by akha666** [sdex/AndroidIDeditor#7]
Some App doesn't detected.
For ex. AuthLogics
https://play.google.com/store/apps/details?id=authlogics.softToken&gl=US

**Comment by sdex** [comment]
If the app is not listed it means that this app doesn't use the system ID.

**Comment by akha666** [comment]
Thank you for your response
Actually, this app uses Device ID. Could it be changed?
![IMG_20220420_112127](https://user-images.githubusercontent.com/28590461/164196290-b68580d7-35e1-4c7c-85b0-e0edccd88873.jpg)

**Comment by sdex** [comment]
The app doesn't use the system ID. 
If you uninstall the app and install it again the ID is different. It's persistent in the case of the system device ID.
Also, it has a different format. I am convinced that the app generates random 16 digits ID during the first launch and stores it in its own preferences.

**Comment by akha666** [comment]
Could you advice? How to change this?

**Comment by sdex** [comment]
This is an app-specific problem, `AndroidIDeditor` is a versatile tool. 
You need to figure out where the app stores the ID, it might be shared preferences or sqlite database.
